# frozen_string_literal: true

require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe '/projects', type: :request do
  # This should return the minimal set of attributes required to create a valid
  # Project. As you add validations to Project, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    { name: 'Project A' }
  end

  let(:invalid_attributes) do
    { name: nil }
  end

  # This should return the minimal set of values that should be in the headers
  # in order to pass any filters (e.g. authentication) defined in
  # Api::V1::ProjectsController, or in your router and rack
  # middleware. Be sure to keep this updated too.
  let(:valid_headers) do
    {}
  end

  let!(:project) { create(:project, valid_attributes) }

  describe 'GET /index' do
    it 'renders a successful response' do
      get api_v1_projects_url, headers: valid_headers, as: :json
      expect(response).to be_successful
    end
  end

  describe 'GET /show' do
    it 'renders a successful response' do
      get api_v1_project_url(project), as: :json
      expect(response).to be_successful
    end
  end

  describe 'POST /create' do
    context 'with valid parameters' do
      it 'creates a new Project' do
        expect do
          post api_v1_projects_url,
               params: valid_attributes, headers: valid_headers, as: :json
        end.to change(Project, :count).by(1)
      end

      it 'renders a JSON response with the new project' do
        post api_v1_projects_url,
             params: valid_attributes, headers: valid_headers, as: :json
        expect(response).to have_http_status(:created)
      end
    end

    context 'with invalid parameters' do
      it 'does not create a new Project' do
        expect do
          post api_v1_projects_url,
               params: invalid_attributes, as: :json
        end.to change(Project, :count).by(0)
      end

      it 'renders a JSON response with errors for the new project' do
        post api_v1_projects_url,
             params: invalid_attributes, headers: valid_headers, as: :json
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe 'PATCH /update' do
    context 'with valid parameters' do
      new_name = 'Project B'
      let(:new_attributes) do
        { name: new_name }
      end

      it 'updates the requested project' do
        patch api_v1_project_url(project),
              params: new_attributes, headers: valid_headers, as: :json
        project.reload
        expect(project.name).to eql(new_name)
      end

      it 'renders a JSON response with the project' do
        patch api_v1_project_url(project),
              params: new_attributes, headers: valid_headers, as: :json
        expect(response).to have_http_status(:ok)
      end
    end

    context 'with invalid parameters' do
      it 'renders a JSON response with errors for the project' do
        patch api_v1_project_url(project),
              params: invalid_attributes, headers: valid_headers, as: :json
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe 'DELETE /destroy' do
    it 'destroys the requested project' do
      expect do
        delete api_v1_project_url(project), headers: valid_headers, as: :json
      end.to change(Project, :count).by(-1)
    end
  end
end
