# frozen_string_literal: true

require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe '/teams', type: :request do
  # This should return the minimal set of attributes required to create a valid
  # Team. As you add validations to Team, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    { name: 'Team A' }
  end

  let(:invalid_attributes) do
    { name: nil }
  end

  # This should return the minimal set of values that should be in the headers
  # in order to pass any filters (e.g. authentication) defined in
  # Api::V1::TeamsController, or in your router and rack
  # middleware. Be sure to keep this updated too.
  let(:valid_headers) do
    {}
  end

  describe 'GET /index' do
    it 'renders a successful response' do
      Team.create! valid_attributes
      get api_v1_teams_url, headers: valid_headers, as: :json
      expect(response).to be_successful
    end
  end

  describe 'GET /show' do
    it 'renders a successful response' do
      team = Team.create! valid_attributes
      get api_v1_team_url(team), as: :json
      expect(response).to be_successful
    end
  end

  describe 'POST /create' do
    context 'with valid parameters' do
      it 'creates a new Team' do
        expect do
          post api_v1_teams_url,
               params: valid_attributes, headers: valid_headers, as: :json
        end.to change(Team, :count).by(1)
      end

      it 'renders a JSON response with the new team' do
        post api_v1_teams_url,
             params: valid_attributes, headers: valid_headers, as: :json
        expect(response).to have_http_status(:created)
      end
    end

    context 'with invalid parameters' do
      it 'does not create a new Team' do
        expect do
          post api_v1_teams_url,
               params: invalid_attributes, as: :json
        end.to change(Team, :count).by(0)
      end

      it 'renders a JSON response with errors for the new team' do
        post api_v1_teams_url,
             params: invalid_attributes, headers: valid_headers, as: :json
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe 'PATCH /update' do
    context 'with valid parameters' do
      let(:new_name) { 'Team B' }
      let(:new_attributes) do
        { name: new_name }
      end

      it 'updates the requested team' do
        team = Team.create! valid_attributes
        patch api_v1_team_url(team),
              params: new_attributes, headers: valid_headers, as: :json
        team.reload
        expect(team.name).to eql(new_name)
      end

      it 'renders a JSON response with the team' do
        team = Team.create! valid_attributes
        patch api_v1_team_url(team),
              params: new_attributes, headers: valid_headers, as: :json
        expect(response).to have_http_status(:ok)
      end
    end

    context 'with invalid parameters' do
      it 'renders a JSON response with errors for the team' do
        team = Team.create! valid_attributes
        patch api_v1_team_url(team),
              params: invalid_attributes, headers: valid_headers, as: :json
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe 'DELETE /destroy' do
    it 'destroys the requested team' do
      team = Team.create! valid_attributes
      expect do
        delete api_v1_team_url(team), headers: valid_headers, as: :json
      end.to change(Team, :count).by(-1)
    end
  end
end
