# This is the configuration used to check the rubocop source code.

require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-rspec_rails
  - rubocop-factory_bot

Documentation:
  Enabled: false

MultipleMemoizedHelpers:
  Enabled: false
